version: '3.3'
services:
  haproxy:
    image: haproxy:alpine
    configs: 
      - haproxy_cfg
    networks:
      - dbs
    command: haproxy -f /haproxy_cfg
    deploy:
      labels:
        - traefik.enable=true
        # PostgreSQL Master (TCP 5000)
        - traefik.tcp.routers.pg-master.rule=HostSNI(`*`)
        - traefik.tcp.routers.pg-master.entrypoints=pg-master
        - traefik.tcp.services.pg-master.loadbalancer.server.port=5000
        # PostgreSQL Replica (TCP 5001)
        - traefik.tcp.routers.pg-replica.rule=HostSNI(`*`)
        - traefik.tcp.routers.pg-replica.entrypoints=pg-replica
        - traefik.tcp.services.pg-replica.loadbalancer.server.port=5001
        # REST API (HTTPS 443)
        - traefik.http.routers.api.rule=Host(`api.example.com`)  # Update domain
        - traefik.http.routers.api.entrypoints=websecure
        - traefik.http.routers.api.tls=true
        - traefik.http.routers.api.tls.certresolver=myresolver
        - traefik.http.services.api.loadbalancer.server.port=8008

  etcd:
    image: quay.io/coreos/etcd:v3.1.2
    configs:
      - etcd_cfg
      - source: traefik_dynamic
        target: /var/run/traefik/dynamic/traefik_dynamic.yml
    networks:
      - app-internal
    command: /bin/sh /etcd_cfg
    volumes:
      - /mnt/data/traefik/dynamic:/var/run/traefik/dynamic

  dbnode1:
    image: seocahill/patroni:1.2.5
    secrets:
      - patroni.yml
    configs:
      - source: notification.py
        target: /home/postgres/notification.py
      - source: notification.sh
        target: /home/postgres/notification.sh
    environment:
      - PATRONI_NAME=dbnode1
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode1
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode1:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode1:8008
    env_file:
      - stack.env
    networks:
      - app-internal
      - traefik-public
    entrypoint: patroni
    command: /run/secrets/patroni.yml

  dbnode2:
    image: seocahill/patroni:1.2.5
    secrets:
      - patroni.yml
    configs:
      - source: notification.py
        target: /home/postgres/notification.py
      - source: notification.sh
        target: /home/postgres/notification.sh
    environment:
      - PATRONI_NAME=dbnode2
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode2
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode2:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode2:8008
    env_file:
      - stack.env
    networks:
      - app-internal
      - traefik-public
    entrypoint: patroni
    command: /run/secrets/patroni.yml

  dbnode3:
    image: seocahill/patroni:1.2.5
    secrets:
      - patroni.yml
    configs:
      - source: notification.py
        target: /home/postgres/notification.py
      - source: notification.sh
        target: /home/postgres/notification.sh
    environment:
      - PATRONI_NAME=dbnode3
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode3
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode3:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode3:8008
    env_file:
      - stack.env
    networks:
      - app-internal
      - traefik-public
    entrypoint: patroni
    command: /run/secrets/patroni.yml

configs:
  traefik_dynamic:
    file: traefik-dynamic-patroni-stack.yml
  etcd_cfg:
    file: config/etcd.sh
  cron_archive:
    file: cron/archive.sh
  cron_restore_archive:
    file: cron/restore_archive.sh
  cron_dump:
    file: cron/dump.sh
  cron_restore_dump:
    file: cron/restore_dump.sh
  notification.py:
    file: callbacks/notification.py
  notification.sh:
    file: callbacks/notification.sh

networks:
  app-internal:
    external: true
  traefik-public:
    external: true 


secrets:
  patroni.yml:
    file: patroni.yml

