version: '3.3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.1.2
    configs:
      - etcd_cfg
      - source: traefik_dynamic
        target: /var/run/traefik/dynamic/traefik_dynamic.yml
    networks:
      - app-internal
    command: /bin/sh /etcd_cfg
    volumes:
      - /mnt/data/traefik/dynamic:/var/run/traefik/dynamic

  dbnode1:
    image: seocahill/patroni:1.2.5
    secrets:
      - patroni.yml
    environment:
      - PATRONI_NAME=dbnode1
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode1
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode1:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode1:8008
    env_file:
      - stack.env
    networks:
      - app-internal
      - traefik-public
    entrypoint: patroni
    command: /run/secrets/patroni.yml
    deploy:
      labels:
        - traefik.enable=true
        # Unique router name for master connection on this node
        - traefik.tcp.routers.postgres-master-1.entrypoints=postgres-master
        - traefik.tcp.routers.postgres-master-1.rule=HostSNI(`*`)
        - traefik.tcp.services.postgres-master-1.loadbalancer.server.port=5432
        # Unique router name for replica connection on this node
        - traefik.tcp.routers.postgres-replica-1.entrypoints=postgres-replica
        - traefik.tcp.routers.postgres-replica-1.rule=HostSNI(`*`)
        - traefik.tcp.services.postgres-replica-1.loadbalancer.server.port=5432
        # Unique router name for API
        - traefik.http.routers.patroni-api-1.entrypoints=patroni-api
        - traefik.http.routers.patroni-api-1.rule=PathPrefix(`/`)
        - traefik.http.services.patroni-api-1.loadbalancer.server.port=8008

  dbnode2:
    image: seocahill/patroni:1.2.5
    secrets:
      - patroni.yml
    environment:
      - PATRONI_NAME=dbnode2
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode2
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode2:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode2:8008
    env_file:
      - stack.env
    networks:
      - app-internal
      - traefik-public
    entrypoint: patroni
    command: /run/secrets/patroni.yml
    deploy:
      labels:
        - traefik.enable=true
        # Unique router name for master connection on this node
        - traefik.tcp.routers.postgres-master-2.entrypoints=postgres-master
        - traefik.tcp.routers.postgres-master-2.rule=HostSNI(`*`)
        - traefik.tcp.services.postgres-master-2.loadbalancer.server.port=5432
        # Unique router name for replica connection on this node
        - traefik.tcp.routers.postgres-replica-2.entrypoints=postgres-replica
        - traefik.tcp.routers.postgres-replica-2.rule=HostSNI(`*`)
        - traefik.tcp.services.postgres-replica-2.loadbalancer.server.port=5432
        # Unique router name for API
        - traefik.http.routers.patroni-api-2.entrypoints=patroni-api
        - traefik.http.routers.patroni-api-2.rule=PathPrefix(`/`)
        - traefik.http.services.patroni-api-2.loadbalancer.server.port=8008

  dbnode3:
    image: seocahill/patroni:1.2.5
    secrets:
      - patroni.yml
    environment:
      - PATRONI_NAME=dbnode3
      - PATRONI_POSTGRESQL_DATA_DIR=data/dbnode3
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=dbnode3:5432
      - PATRONI_RESTAPI_CONNECT_ADDRESS=dbnode3:8008
    env_file:
      - stack.env
    networks:
      - app-internal
      - traefik-public
    entrypoint: patroni
    command: /run/secrets/patroni.yml
    deploy:
      labels:
        - traefik.enable=true
        # Unique router name for master connection on this node
        - traefik.tcp.routers.postgres-master-3.entrypoints=postgres-master
        - traefik.tcp.routers.postgres-master-3.rule=HostSNI(`*`)
        - traefik.tcp.services.postgres-master-3.loadbalancer.server.port=5432
        # Unique router name for replica connection on this node
        - traefik.tcp.routers.postgres-replica-3.entrypoints=postgres-replica
        - traefik.tcp.routers.postgres-replica-3.rule=HostSNI(`*`)
        - traefik.tcp.services.postgres-replica-3.loadbalancer.server.port=5432
        # Unique router name for API
        - traefik.http.routers.patroni-api-3.entrypoints=patroni-api
        - traefik.http.routers.patroni-api-3.rule=PathPrefix(`/`)
        - traefik.http.services.patroni-api-3.loadbalancer.server.port=8008

configs:
  traefik_dynamic:
    file: traefik-dynamic-patroni-stack.yml
  etcd_cfg:
    file: config/etcd.sh
  cron_archive:
    file: cron/archive.sh
  cron_restore_archive:
    file: cron/restore_archive.sh
  cron_dump:
    file: cron/dump.sh
  cron_restore_dump:
    file: cron/restore_dump.sh
  notification.py:
    file: callbacks/notification.py
  notification.sh:
    file: callbacks/notification.sh

networks:
  app-internal:
    external: true
  traefik-public:
    external: true 


secrets:
  patroni.yml:
    file: patroni.yml

