tcp:
  routers:
    postgres-master-router:
      entryPoints:
        - "postgres-master"
      rule: "HostSNI(`*`)"
      service: "postgres-master"

    postgres-replica-router:
      entryPoints:
        - "postgres-replica"
      rule: "HostSNI(`*`)"
      service: "postgres-replica"

  services:
    postgres-master:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"

    postgres-replica:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"

http:
  routers:
    patroni-api-router:
      entryPoints:
        - "patroni-api"
      rule: "PathPrefix(`/`)"
      service: "patroni-api"

  services:
    patroni-api:
      loadBalancer:
        healthCheck:
          path: "/master"
          interval: "5s"
          timeout: "3s"
          port: 8008
          followRedirects: true
          headers:
            User-Agent: "Traefik Health Check"
          scheme: "https"
        servers:
          - url: "https://dbnode1:8008"
          - url: "https://dbnode2:8008"
          - url: "https://dbnode3:8008"