tcp:
  routers:
    postgres:
      entryPoints:
        - pg
      rule: "HostSNI(`postgres.coastalsites.dev`)"
      service: postgres
      tls:
        passthrough: true
  services:
    postgres:
      loadBalancer:
        servers:
          - address: dbnode1:5432
          - address: dbnode2:5432
          - address: dbnode3:5432
        passHostHeader: true
  middlewares:
    postgres:
      headers:
        customRequestHeaders:
          X-Forwarded-Host: "postgres.coastalsites.dev"
        customResponseHeaders:
          X-Forwarded-Host: "postgres.coastalsites.dev"
        sslRedirect: true
        customFrameOptionsValue: "ALLOWALL"
