tcp:
  routers:
    postgres-master:
      entryPoints: ["postgres-master"]
      rule: "HostSNI(`*`)"
      service: postgres-master-service
      tls:
        passthrough: true

    postgres-replica:
      entryPoints: ["postgres-replica"]
      rule: "HostSNI(`*`)"
      service: postgres-replica-service
      tls:
        passthrough: true

  services:
    postgres-master-service:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"
        healthCheck:
          port: 8008
          interval: "5s"
          timeout: "5s"

    postgres-replica-service:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"
        healthCheck:
          port: 8008
          interval: "5s"
          timeout: "5s"

http:
  routers:
    patroni-api:
      entryPoints: ["patroni-api"]
      rule: "PathPrefix(`/`)"
      service: patroni-api-service

  services:
    patroni-api-service:
      loadBalancer:
        healthCheck:
          path: "/master"
          interval: "5s"
          timeout: "5s"
        servers:
          - url: "http://dbnode1:8008"
          - url: "http://dbnode2:8008"
          - url: "http://dbnode3:8008"