tcp:
  routers:
    postgres-master-router:
      entryPoints:
        - "postgres-master"
      rule: "HostSNI(`*`)"
      service: "postgres-master"

    postgres-replica-router:
      entryPoints:
        - "postgres-replica"
      rule: "HostSNI(`*`)"
      service: "postgres-replica"

  services:
    postgres-master:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"

    postgres-replica:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"

http:
  routers:
    patroni-api-router:
      entryPoints:
        - "patroni-api"
      rule: "PathPrefix(`/`)"
      service: "patroni-api"

  services:
    patroni-api:
      loadBalancer:
        # More resilient health check config
        healthCheck:
          path: "/"                  # Changed to root path first for basic connectivity test
          interval: "10s"            # Increased interval
          timeout: "5s"              # Increased timeout
          followRedirects: true
          headers:
            User-Agent: "Traefik Health Check"
          scheme: "http"
        servers:
          - url: "http://dbnode1:8008"
          - url: "http://dbnode2:8008"
          - url: "http://dbnode3:8008"