http:
  services:
    patroni-api:
      loadBalancer:
        port: 8008
        healthCheck:
          path: /master
          interval: 10s
          timeout: 5s
        serversTransport: custom-transport  # Add custom transport
        servers: []  # Let Docker DNS handle discovery

tcp:
  services:
    postgres-master:
      loadBalancer:
        port: 5000
        serversTransport: custom-transport  # Add custom transport
        servers: []  # Empty list for dynamic discovery

    postgres-replica:
      loadBalancer:
      port: 5001
      serversTransport: custom-transport  # Add custom transport
      servers: []  # Empty list for dynamic discovery

serversTransports:
  custom-transport:
    insecureSkipVerify: true
    rootCAs:
      - /var/run/secrets/ca.crt