tcp:
  routers:
    postgres:
      entryPoints:
        - pg
      rule: "HostSNI(`postgres.coastalsites.dev`)"
      service: postgres
      tls: {} 
  services:
    postgres:
      loadBalancer:
        servers:
          - address: dbnode1:5432
          - address: dbnode2:5432
          - address: dbnode3:5432
        serversTransport: postgres-tls
  serversTransports:
    postgres-tls:
      insecureSkipVerify: true
