tcp:
  routers:
    postgres-master-router:
      entryPoints:
        - "postgres-master"
      rule: "HostSNI(`*`)"
      service: "postgres-master"

    postgres-replica-router:
      entryPoints:
        - "postgres-replica"
      rule: "HostSNI(`*`)"
      service: "postgres-replica"

  services:
    postgres-master:
      loadBalancer:
        servers:
          - address: "ha-patroni-postgresql_dbnode1:5432"
          - address: "ha-patroni-postgresql_dbnode2:5432"
          - address: "ha-patroni-postgresql_dbnode3:5432"

    postgres-replica:
      loadBalancer:
        servers:
          - address: "ha-patroni-postgresql_dbnode1:5432"
          - address: "ha-patroni-postgresql_dbnode2:5432"
          - address: "ha-patroni-postgresql_dbnode3:5432"

http:
  routers:
    patroni-api-router:
      entryPoints:
        - "patroni-api"
      rule: "PathPrefix(`/`)"
      service: "patroni-api"

  services:
    patroni-api:
      loadBalancer:
        # More resilient health check config
        healthCheck:
          interval: "10s"            # Increased interval
          timeout: "5s"              # Increased timeout
          headers:
            User-Agent: "Traefik Health Check"
        servers:
          - url: "http://ha-patroni-postgresql_dbnode1:8008"
          - url: "http://ha-patroni-postgresql_dbnode2:8008"
          - url: "http://ha-patroni-postgresql_dbnode3:8008"