tcp:
  routers:
    postgres-master-router:
      entryPoints:
        - "postgres-master"
      rule: "HostSNI(`*`)"
      service: "postgres-master"

    postgres-replica-router:
      entryPoints:
        - "postgres-replica"
      rule: "HostSNI(`*`)"
      service: "postgres-replica"

    patroni-api-router:
      entryPoints:
        - "patroni-api"
      rule: "HostSNI(`*`)"
      service: "patroni-api@http"

  services:
    postgres-master:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"
        # TCP services use Traefik's built-in health checking which works with Patroni

    postgres-replica:
      loadBalancer:
        servers:
          - address: "dbnode1:5432"
          - address: "dbnode2:5432"
          - address: "dbnode3:5432"

http:
  routers:
    patroni-api:
      entryPoints: ["patroni-api"]
      rule: "PathPrefix(`/`)"
      service: patroni-api-service

  services:
    patroni-api:
      loadBalancer:
        servers:
          - url: "http://dbnode1:8008"
          - url: "http://dbnode2:8008"
          - url: "http://dbnode3:8008"
        healthCheck:
          path: "/master"
          interval: "5s"
          timeout: "3s"